### PR TITLE
added cff and badge/citation in readme

### PR DESCRIPTION
**Pull request by JFRudzinski**

### CODE REVIEW

**Comment by JFRudzinski** [comment]
@ladinesa Do you have admin access to this repo?

@ladinesa @JosePizarro3 Let me know if you want me to change anything about the description in the ReadMe I just made it very short.

**Review by ladinesa — APPROVED** [review]

**Comment by ladinesa** [comment]
> @ladinesa Do you have admin access to this repo?

yes i do

**Comment by JFRudzinski** [comment]
Ok, so I need you to go to your Zenodo account (or create one), go to your profile and then click the github integration tab (see attached). Find this repo in the list, and then flip the switch to on. I guess you should also do runschema, electronicparsers, and atomisticparsers while you are at it

Screenshot from 2024-09-26 15-59-07

**Comment by ladinesa** [comment]
done

**Pull request merged**
