### PR TITLE
updated MD workflow metainfo

### LINKED ISSUE #4: H5MD metainfo
linked with h5md parser dev

### PR DESCRIPTION
**Pull request by JFRudzinski**
@ladinesa this should be the same that you already saw in the NOMAD repo, but maybe just take a quick look. 

small question: should we be using single quotes throughout? I feel like it keeps going back and forth, but maybe it's just me..

### CODE REVIEW

**Comment by ladinesa** [comment]
> @ladinesa this should be the same that you already saw in the NOMAD repo, but maybe just take a quick look.
> 
> small question: should we be using single quotes throughout? I feel like it keeps going back and forth, but maybe it's just me..

if they switched to double quotes in nomad then we switch to double quotes.

**Comment by JosePizarro3** [comment]
> > small question: should we be using single quotes throughout? I feel like it keeps going back and forth, but maybe it's just me..
> 
> if they switched to double quotes in nomad then we switch to double quotes.

I think this is coming from Ruff, and they did not specify anything about quotation (thought I was googling and [it is easy to set this up](https://docs.astral.sh/ruff/formatter/)).

We have now the VSCode with the Ruff extension, so I am guessing we are going to face a lot of situations in which a bunch of code is going to be reformatted. Is it not better to ask Ahmed for help here, @ladinesa, or should it be our responsability?

**Comment by JFRudzinski** [comment]
ok, well, I will not worry about it for now.

so...Can I merge this?

**Comment by ladinesa** [comment]
> > > small question: should we be using single quotes throughout? I feel like it keeps going back and forth, but maybe it's just me..
> > 
> > 
> > if they switched to double quotes in nomad then we switch to double quotes.
> 
> I think this is coming from Ruff, and they did not specify anything about quotation (thought I was googling and [it is easy to set this up](https://docs.astral.sh/ruff/formatter/)).
> 
> We have now the VSCode with the Ruff extension, so I am guessing we are going to face a lot of situations in which a bunch of code is going to be reformatted. Is it not better to ask Ahmed for help here, @ladinesa, or should it be our responsability?

yes, it is simply defining it in the ruff format file. we should apply the same style that is used in nomad.

**Comment by ladinesa** [comment]
> ok, well, I will not worry about it for now.
> 
> so...Can I merge this?

can you please also use the schema from the plugin in the h5md parser? thanks. also, please determine if new tests are necessary.

**Comment by JFRudzinski** [comment]
> can you please also use the schema from the plugin in the h5md parser?

Sorry, what do you mean exactly?

**Comment by ladinesa** [comment]
> > can you please also use the schema from the plugin in the h5md parser?
> 
> Sorry, what do you mean exactly?

change all the from nomad.datamodel.metainfo.simulation.workflow import * to from simulationworkflowshchema import *

**Comment by JFRudzinski** [comment]
> > > can you please also use the schema from the plugin in the h5md parser?
> > 
> > 
> > Sorry, what do you mean exactly?
> 
> change all the from nomad.datamodel.metainfo.simulation.workflow import * to from simulationworkflowshchema import *

Ah got it. Yes, I will do that shortly, thanks.

**Pull request merged**
