### PR TITLE
Remove dependency links to git branches

### PR DESCRIPTION
**Pull request by ndaelman-hu**

### CODE REVIEW

**Comment by ndaelman-hu** [comment]
So, I fixed one thing with the dependencies that else breaks the distro dev

**Comment by ndaelman-hu** [comment]
The test still fails, but this is just for `python3.9`, while `3.10` and `3.11` are fine.
The common change in dependencies is `importlib-resources==6.4.5`, which is only present for `3.9`.

Screenshot from 2024-11-21 15-49-17

**Comment by ndaelman-hu** [comment]
Yep, it was the dependency. @ladinesa @blueraft is it fine if I throw it out?

**Comment by blueraft** [comment]
Looks fine by me, but Alvin should probably make the call here

**Comment by ndaelman-hu** [comment]
> Looks fine by me, but Alvin should probably make the call here

I just removed an older fashion of loading the submodules. Anyhow, I'm fine waiting, as long as we don't run into issues.
@JFRudzinski will you keep an eye?

**Review by JFRudzinski — APPROVED** [review]
It seems fine to me, but maybe let's just wait for Alvin to 100% confirm since I think it's not urgent

**Comment by ladinesa** [comment]
> Yep, it was the dependency. @ladinesa @blueraft is it fine if I throw it out?

yes pls remove the git dep. about the second change, it is ok if this works. i have to put this since i have old imports like from simulationworkflowschema import MolecularDynamics which do not anymore work. so if this is fixed already then pls remove the hack

**Comment by JFRudzinski** [comment]
I finally was able to test this. It appears to me that this change actually causes an issue:

```bash
ImportError while loading conftest '/home/jfrudzinski/work/soft/nomad-distro-dev/packages/nomad-schema-plugin-simulation-workflow/tests/conftest.py'.
tests/conftest.py:26: in <module>
    from nomad.normalizing import normalizers
../nomad-FAIR/nomad/normalizing/__init__.py:128: in <module>
    NormalizerInterfaceNew(entry_point.load(), entry_point.level)
../../.venv/lib/python3.12/site-packages/simulationworkflownormalizer/__init__.py:24: in load
    from .normalizer import SimulationWorkflowNormalizer
../../.venv/lib/python3.12/site-packages/simulationworkflownormalizer/normalizer.py:21: in <module>
    from simulationworkflowschema import (
E   ImportError: cannot import name 'SinglePoint' from 'simulationworkflowschema' (/home/jfrudzinski/work/soft/nomad-distro-dev/packages/nomad-schema-plugin-simulation-workflow/simulationworkflowschema/__init__.py)
```

When testing with the current develop branch, all my tests pass.

**Comment by JFRudzinski** [comment]
covered by #40 but replaced the import hack to avoid errors for now

**Pull request closed without merging**
